export const SCHEMA_VERSION = 'investo.inquiry.v1';
export const FORM_ID = 'strategy-check-v1';
export const FORM_NAME = 'Investo Strategy Check';
export const CONSENT_VERSION = '2026-09-24-v1';
const label = (de, en, fr) => ({ de, en, fr });
const option = (value, de, en, fr) => ({ value, label: label(de, en, fr) });
export const fields = [
  { key: 'purchase_intent', step: 1, label: label('Kaufabsicht', 'Purchase purpose', 'Objectif d’achat'), options: [option('investment','Kapitalanlage','Investment','Investissement'),option('own_use','Eigennutzung','Personal use','Usage personnel'),option('both','Beides','Both','Les deux')] },
  { key: 'purchase_timeframe', step: 1, label: label('Kaufzeitraum','Purchase timeframe','Délai d’achat'), options: [option('0_3_months','In 0–3 Monaten','Within 0–3 months','Dans 0 à 3 mois'),option('3_6_months','In 3–6 Monaten','Within 3–6 months','Dans 3 à 6 mois'),option('6_12_months','In 6–12 Monaten','Within 6–12 months','Dans 6 à 12 mois'),option('over_12_months','Später als 12 Monate','More than 12 months','Dans plus de 12 mois'),option('exploring','Noch offen','Still exploring','À définir')] },
  { key: 'preferred_region', step: 1, type: 'text', maxLength: 160, label: label('Wunschregion','Preferred region','Région souhaitée') },
  { key: 'property_type', step: 1, label: label('Bevorzugte Objektart','Preferred property type','Type de bien souhaité'), options: [option('apartment','Wohnung','Apartment','Appartement'),option('house','Haus','House','Maison'),option('apartment_building','Mehrfamilienhaus','Apartment building','Immeuble de rapport'),option('commercial','Gewerbeimmobilie','Commercial property','Immobilier commercial'),option('open','Noch offen','Open to options','Sans préférence')] },
  { key: 'investment_goals', step: 1, multiple: true, required: true, label: label('Investmentziele','Investment goals','Objectifs d’investissement'), options: [option('Altersvorsorge','Altersvorsorge','Retirement planning','Préparation de la retraite'),option('Cashflow','Cashflow','Cash flow','Revenus réguliers'),option('Diversifikation','Diversifikation','Diversification','Diversification'),option('Kapitalerhalt','Kapitalerhalt','Capital preservation','Préservation du capital'),option('Steueroptimierung','Steueroptimierung','Tax optimisation','Optimisation fiscale'),option('Vermögensaufbau','Vermögensaufbau','Wealth building','Constitution de patrimoine')] },
  { key: 'available_equity_eur', step: 2, type: 'number', min: 0, max: 1000000000, label: label('Verfügbares Eigenkapital (€)','Available equity (€)','Apport disponible (€)') },
  { key: 'purchase_budget_eur', step: 2, type: 'number', min: 1, max: 1000000000, label: label('Geplantes Kaufbudget (€)','Planned purchase budget (€)','Budget d’achat prévu (€)') },
  { key: 'income_band', step: 2, required: true, label: label('Monatliches Nettohaushaltseinkommen','Monthly net household income','Revenu net mensuel du foyer'), options: [option('Unter 3.000 €','Unter 3.000 €','Under €3,000','Moins de 3 000 €'),option('3.000–5.000 €','3.000–5.000 €','€3,000–5,000','3 000–5 000 €'),option('5.001–8.000 €','5.001–8.000 €','€5,001–8,000','5 001–8 000 €'),option('8.001–12.000 €','8.001–12.000 €','€8,001–12,000','8 001–12 000 €'),option('Über 12.000 €','Über 12.000 €','Over €12,000','Plus de 12 000 €')] },
  { key: 'experience_raw', step: 2, required: true, label: label('Erfahrung mit Immobilien','Property investment experience','Expérience immobilière'), options: [option('Einsteiger','Einsteiger','Beginner','Débutant'),option('Erste Erfahrungen','Erste Erfahrungen','Some experience','Premières expériences'),option('Erfahren','Erfahren','Experienced','Expérimenté')] },
  { key: 'employment_status', step: 2, label: label('Beruflicher Status','Employment status','Situation professionnelle'), options: [option('employed','Angestellt','Employed','Salarié'),option('self_employed','Selbstständig / Unternehmer','Self-employed / business owner','Indépendant / entrepreneur'),option('civil_servant','Verbeamtet','Civil servant','Fonctionnaire'),option('retired','Im Ruhestand','Retired','Retraité'),option('student','In Ausbildung / Studium','In education','Étudiant / en formation'),option('other','Sonstiges','Other','Autre')] },
  { key: 'existing_property_count', step: 2, type: 'number', min: 0, max: 10000, label: label('Anzahl bestehender Immobilien','Properties currently owned','Nombre de biens déjà détenus') },
  { key: 'first_name', step: 3, required: true, type: 'text', maxLength: 80, autoComplete: 'given-name', label: label('Vorname','First name','Prénom') },
  { key: 'last_name', step: 3, required: true, type: 'text', maxLength: 80, autoComplete: 'family-name', label: label('Nachname','Last name','Nom') },
  { key: 'email', step: 3, required: true, type: 'email', maxLength: 254, autoComplete: 'email', label: label('E-Mail-Adresse','Email address','Adresse e-mail') },
  { key: 'phone', step: 3, required: true, type: 'tel', maxLength: 40, autoComplete: 'tel', label: label('Telefonnummer mit Ländervorwahl (+49 …)','Phone with country code (+49 …)','Téléphone avec indicatif (+33 …)') },
  { key: 'preferred_contact_method', step: 3, label: label('Bevorzugter Kontaktweg','Preferred contact method','Moyen de contact préféré'), options: [option('email','E-Mail','Email','E-mail'),option('phone','Telefon','Phone','Téléphone'),option('either','Telefon oder E-Mail','Phone or email','Téléphone ou e-mail')] },
  { key: 'preferred_contact_time', step: 3, label: label('Bevorzugte Kontaktzeit','Preferred contact time','Horaire de contact préféré'), options: [option('morning','Vormittags (9–12 Uhr)','Morning (09:00–12:00)','Matin (9 h–12 h)'),option('afternoon','Nachmittags (12–17 Uhr)','Afternoon (12:00–17:00)','Après-midi (12 h–17 h)'),option('evening','Abends (17–20 Uhr)','Evening (17:00–20:00)','Soir (17 h–20 h)'),option('anytime','Keine Präferenz','No preference','Sans préférence')] },
];
export const consentText = {
  contact: label('Ich willige ein, dass Investo Immobilien meine Angaben zur Bearbeitung meiner Anfrage verarbeitet und mich über den gewählten Kontaktweg kontaktiert. Ich kann diese Einwilligung jederzeit mit Wirkung für die Zukunft unter info@investo-immobilien.de widerrufen. Weitere Informationen stehen in der Datenschutzerklärung.', 'I consent to Investo Immobilien processing my details to handle my enquiry and contacting me by my chosen contact method. I can withdraw this consent at any time for the future by emailing info@investo-immobilien.de. Further information is available in the privacy policy.', 'J’accepte qu’Investo Immobilien traite mes informations pour répondre à ma demande et me contacte par le moyen choisi. Je peux retirer ce consentement à tout moment pour l’avenir à info@investo-immobilien.de. Consultez la politique de confidentialité pour plus d’informations.'),
  newsletter: label('Ich möchte zusätzlich den E-Mail-Newsletter von Investo Immobilien erhalten. Diese Einwilligung ist freiwillig und unabhängig von meiner Anfrage. Ich kann sie jederzeit über den Abmeldelink oder per E-Mail an info@investo-immobilien.de widerrufen.', 'I would also like to receive the Investo Immobilien email newsletter. This consent is optional and independent of my enquiry. I can withdraw it at any time using the unsubscribe link or by emailing info@investo-immobilien.de.', 'Je souhaite également recevoir la newsletter d’Investo Immobilien par e-mail. Ce consentement est facultatif et indépendant de ma demande. Je peux le retirer à tout moment via le lien de désinscription ou à info@investo-immobilien.de.'),
};

